name: Discord Bot/Genova workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: python:3.9-slim
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: python-m pip install --upgrade pip | pip install -r requirements.txt 

      - name: Format Python Files
        run: black .

      - name: Check Python Formatting
        run: black --check .

        